In [1]:
import pandas as pd 
import numpy as np 
from tqdm import tqdm

#ML
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.metrics import accuracy_score
from scipy import stats
import matplotlib.pyplot as plt
import os
import random
from sklearn.metrics import r2_score
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from scipy import stats
import matplotlib.pyplot as plt
import os

import warnings
warnings.filterwarnings("ignore")

/opt/anaconda3/envs/EDA/lib/python3.12/site-packages/sklearn/utils/_param_validation.py:14: UserWarning: A NumPy version >=1.22.4 and <2.3.0 is required for this version of SciPy (detected version 2.4.2)
  from scipy.sparse import csr_matrix, issparse

In [3]:
complex_thetas = [0.1,0.2,0.3,0.4,0.5]
complex_thetas = [0.3] 
complex_thetas = [0.1] 

# complex_thetas = [0.3] 

simple_beta = [0.02,0.03,0.04,0.05] 

percentile_ths = [10,20,30,40,50,60,70,80,90]

In [5]:
complex_thetas = [0.5] 
all_simple = pd.DataFrame()
all_complex = pd.DataFrame()
all_adoption_type = pd.DataFrame()

nodes_list = [str(i) for i in range(400)]

for seed in tqdm(range(10)):
    for counter_p_small_world in range(1,6):
        
        p_small_world = counter_p_small_world*0.1
        p_small_world = np.round(p_small_world,3)
        #network name set
        network_name = f'smallworld_p0.{counter_p_small_world}_seed{seed}'

        complex_c = pd.DataFrame()
        complex_adoption_type_c = pd.DataFrame()
        #load data sets
        for theta in complex_thetas:
            df_curr_theta = pd.read_csv(f"../result_small_world_rlative_with_adoption_type/unweighted/unweighted_complex_{network_name}_theta_{theta}_prob_0.02_EPH-v3.csv")
            df_curr_theta["th"] = theta
            df_curr_theta_adoption_type = pd.read_csv(f"../result_small_world_rlative_with_adoption_type/unweighted/unweighted_complex_{network_name}_theta_{theta}_prob_0.02_adoption_type.csv")
            df_curr_theta_adoption_type["th"] = theta
            complex_c = pd.concat([complex_c,df_curr_theta])
            complex_adoption_type_c = pd.concat([complex_adoption_type_c,df_curr_theta_adoption_type])
        all_complex = pd.concat([complex_c,all_complex])
        all_adoption_type = pd.concat([complex_adoption_type_c,all_adoption_type])

100%|███████████████████████████████████████████| 10/10 [00:00<00:00, 13.24it/s]

In [7]:
all_complex

,0,1,2,3,4,5,6,7,8,9,...,396,397,398,399,seed,complex_param,simple_infection_ratio,EPH,corr,th
0,NaN,30.0,31.0,32.0,33.0,17.0,32.0,12.0,6.0,19.0,...,33.0,32.0,33.0,33.0,0,0.5,0.524590,8.865412,0.061627,0.5
1,28.0,4.0,28.0,19.0,31.0,26.0,27.0,29.0,29.0,25.0,...,21.0,19.0,0.0,30.0,1,0.5,0.581897,8.399798,0.056854,0.5
2,33.0,NaN,23.0,34.0,34.0,34.0,29.0,18.0,28.0,34.0,...,23.0,34.0,34.0,34.0,2,0.5,0.696517,9.927190,0.043266,0.5
3,29.0,17.0,29.0,29.0,29.0,28.0,30.0,29.0,30.0,10.0,...,28.0,5.0,5.0,4.0,3,0.5,0.536885,8.286323,-0.040006,0.5
4,32.0,16.0,30.0,32.0,31.0,33.0,0.0,24.0,31.0,NaN,...,26.0,NaN,33.0,33.0,4,0.5,0.587234,7.995155,0.102606,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,43.0,37.0,44.0,37.0,38.0,42.0,33.0,44.0,43.0,43.0,...,41.0,45.0,45.0,45.0,195,0.5,0.560185,8.570088,-0.059281,0.5
196,25.0,26.0,27.0,19.0,5.0,0.0,5.0,19.0,16.0,18.0,...,31.0,29.0,28.0,29.0,196,0.5,0.511013,7.054447,0.027588,0.5
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30.0,30.0,NaN,NaN,197,0.5,0.479167,7.055472,-0.067772,0.5
198,28.0,27.0,25.0,24.0,27.0,26.0,26.0,16.0,14.0,17.0,...,28.0,20.0,28.0,28.0,198,0.5,0.495614,8.458444,0.028432,0.5
199,27.0,26.0,20.0,24.0,27.0,26.0,25.0,25.0,25.0,23.0,...,18.0,16.0,27.0,27.0,199,0.5,0.504310,7.328067,0.001326,0.5

In [9]:
all_adoption_type

,0,1,2,3,4,5,6,7,8,9,...,394,395,396,397,398,399,seed,complex_param,simple_infection_ratio,th
0,NaN,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,0,0.5,0.524590,0.5
1,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,1,0.5,0.581897,0.5
2,1.0,NaN,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,...,0.0,1.0,0.0,1.0,1.0,1.0,2,0.5,0.696517,0.5
3,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,3,0.5,0.536885,0.5
4,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,NaN,...,NaN,1.0,0.0,NaN,1.0,1.0,4,0.5,0.587234,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,1.0,1.0,1.0,195,0.5,0.560185,0.5
196,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,196,0.5,0.511013,0.5
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,1.0,1.0,1.0,NaN,NaN,197,0.5,0.479167,0.5
198,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,1.0,198,0.5,0.495614,0.5
199,1.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,0.0,0.0,1.0,1.0,199,0.5,0.504310,0.5